
import './globals.css'
import type { Metadata } from 'next'
import { Navbar } from '../components/navbar'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// const theme = createTheme({
//   palette: {
//     primary: {main:"#daed6e"},
//     secondary: {main:"#444444"}
//   },
//   typography: {
//     body1: {
//       fontStyle: "italic",
//       fontWeight: "bold"
//     }
//   }
// });


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
